/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;

import java.util.List;

/**
 * Testing also loads classes from test dependencies to
 * demonstrate that these dependencies are available to use at runtime.
 */
public final class AppTest {
    @BeforeClass
    public static void setupTesting() {
        List<Class<?>> classes;
        try {
            classes = List.of(
                    org.junit.runner.JUnitCore.class,
                    Class.forName("org.apache.commons.lang3.StringUtils")

            );
        } catch (ClassNotFoundException e) {
            throw new RuntimeException(e);
        }

        StringBuilder msg = new StringBuilder("Setting up testing...\n");
        classes.forEach(c -> msg.append("\tUsing class: ").append(c.getName()).append('\n'));
        msg.append("Done!");

        System.out.print(msg);
    }

    @Test
    public void appCanSimulateWork() {
        App classUnderTest = new App();
        Assert.assertTrue(classUnderTest.simulateWork().contains("Done!"));
    }
}
